#!/bin/sh
GIT_REPO="/srv/repos/xmp3.git"
TMP_DIR=$(mktemp -d)
TMP_GIT_PREFIX=xmp3-tmp

function check() {
    md5sum $1 | awk '{print $1}'
}

function clean() {
    cd
    echo "Removing $TMP_DIR"
    rm -rf $TMP_DIR || exit 1
}

echo "Checking for new post-receive hook..."
git archive --prefix="$TMP_GIT_PREFIX/" --remote="$GIT_REPO" HEAD | tar xf - -C "$TMP_DIR" || exit 1
cd "$TMP_DIR/$TMP_GIT_PREFIX"

# If the post-receive hook has been updated, run that one instead
if [ "$(check $GIT_REPO/hooks/post-receive)" != "$(check post-receive)" ]
then
    echo "post-receive script updated..."
    cp post-receive "$GIT_REPO/hooks/post-receive"
    clean
    exec "$GIT_REPO/hooks/post-receive"
fi

echo "Scheduling Jenkins build"
curl "http://localhost:8080/jenkins/job/XMP3/build?token=SCRIPT_TOKEN" > /dev/null
if [ "$?" -eq 0 ]
then
    echo "Done"
else
    echo "Failed!"
fi

echo "Building documentation"
./waf --build-docs --targets="doxygen" > /dev/null
rsync -r --delete doc/html/ /srv/http/docs/xmp3/ > /dev/null || echo Failed
echo "Done"

clean
