#!/bin/sh

REPO_URL=pm:/srv/repos/swat_build.git
MOD_DIR="$(cd "$(dirname "$0")" && pwd)"
MOD_NAME="$(echo "$MOD_DIR" | awk -F/ '{print $NF}')"

cd "$MOD_DIR"

if [ ! -d swat_build ]
then
    echo "swat_build not found, cloning..."
    git clone "$REPO_URL"
    echo "done"
fi

if [ ! -h build ]
then
    ln -s swat_build/build/ .
fi

cd swat_build

if [ ! -h "$MOD_NAME" ]
then
    ln -s .. "$MOD_NAME"
fi

./waf -m $MOD_NAME $@
